### ISSUE TITLE
vscode plug-in

### ISSUE THREAD

**Issue by soitun** [stevearc/pair-ls#1]
Thank you very much for providing such a good tool, it would be even better if you could implement a VSCODE plug-in。

**Comment by stevearc** [comment]
Sure, I'll give this a shot. I have never really used VSCode so this won't happen quickly, but I'll begin looking into it this week.

**Comment by stevearc** [comment]
Extension created! It's in the marketplace at https://marketplace.visualstudio.com/items?itemName=pair-ls.pair-ls
You can also download the vsix files directly from https://github.com/stevearc/pair-ls-vscode/releases

**Comment by soitun** [comment]
Thank you so much, I can't wait to install and experience it immediately :), I will give feedback after using it
